### ISSUE TITLE
Reuse session to avoid auth for each request

### ISSUE THREAD

**Issue by staticf0x** [Allda/coregio#15]
We noticed coregio is 2 times slower than our original implementation. If I enable the debug logger of `requests` library and set

```py
import http.client as http_client
http_client.HTTPConnection.debuglevel = 1
```

I can see that the flow is always:

- Try `/tags/list`, receive 401 Unauthorized
- Do `/auth`, receive 200 Ok
- Retry `/tags/list`, receive 200 Ok

So it's 3 GET requests per each page. Could the session be reused so that auth is only done one time?

Combined with #14 it means that a repo with 112 tags needs 3 pages, our original implementation made 5 requests (1 try, 1 auth, 3 ok), coregio made 9 (3 try, 3 auth, 3 ok). I guess it should be even possible to get to 4 requests (1 auth, 3 ok).

**Comment by Allda** [comment]
The fixed version is already available https://github.com/Allda/coregio/releases/tag/v0.7.0
